language: go

go:
  - 1.7
  - tip

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgeoip-dev

install:
  - go get github.com/turbobytes/geoipdb

script: go test github.com/turbobytes/geoipdb
